### PR TITLE
Mpi parallel

### PR DESCRIPTION
**Pull request by razugo**

### CODE REVIEW

**Comment by razugo** [comment]
@hyunbumy @avnishn ?

**Review by hyunbumy — COMMENTED** [review]
Add an entry in gitignore for .DS_Store

**Review by avnishn — DISMISSED** [review]
I haven't found anything out of the ordinary. LGTM. 
Also, add Brad's request

**Comment by razugo** [comment]
@avnishn @hyunbumy 
need another review since i pushed so late.

**Review by hyunbumy — APPROVED** [review]

**Pull request merged**
