### PR TITLE
By/cuda Implement CUDA iterative reflection

### PR DESCRIPTION
**Pull request by hyunbumy**
@avnishn @razugo 
I have implemented the iterative reflection ray tracing.
I also optimized the memory layout, which made things quite a bit faster.

Next would be iterative refraction, but I am actually not too sure on how to go about it, so maybe we can discuss it together later.

### CODE REVIEW

**Comment by razugo** [comment]
How do the resulting images look like?

**Comment by hyunbumy** [comment]
> How do the resulting images look like?

untitled

I was able to render a 4k image in about 0.3 sec.
This is without refraction tho.

**Comment by razugo** [comment]
FUCKING BALLER DUDE

**Review by razugo — APPROVED** [review]

**Comment by avnishn** [comment]
HOLY FUCK THOSE ARE INSANE

**Comment by avnishn** [comment]
Wait did you say 0.3 seconds perframe
O.o

**Pull request merged**
