### PR TITLE
cmake changes for MPI and OpenMP

### PR DESCRIPTION
**Pull request by razugo**
Added new commands for cmake.

### CODE REVIEW

**Comment by avnishn** [comment]
Second commit lgtm!

**Review by avnishn — APPROVED** [review]
Second commit is good

**Comment by hyunbumy** [comment]
What is the car struct and stuff?

**Comment by razugo** [comment]
That was initial testing, making sure that I could actually pass custom structs over MPI. I have updated code right now for passing out Vector3 type

**Comment by hyunbumy** [comment]
Gotcha

**Pull request merged**
