### PR TITLE
triangles implemented

### PR DESCRIPTION
**Pull request by razugo**
Working on implementing complex figures, but implemented Triangles. Still a work in progress, but want to keep u guys updated. No need to approve yet.

triangle

### CODE REVIEW

**Comment by razugo** [comment]
Drew triangle from the centers of each sphere. U can see the shadows and the reflection of the point light from above.

triangle from centers

**Comment by hyunbumy** [comment]
Looks good!

**Comment by razugo** [comment]
I rendered a cow.

cow

**Comment by hyunbumy** [comment]
LGTM

**Review by hyunbumy — APPROVED** [review]
LGTM

**Pull request merged**
