### PR TITLE
By/cuda Implement Iterative Refraction

### PR DESCRIPTION
**Pull request by hyunbumy**
@avnishn @razugo 
I was able to implement iterative GPU refraction...
And it turns out the reason why recursive CUDA code did not give the right result was because there was a bug in my code where I put a + instead of a -...
So now both iterative and recursive works!

### CODE REVIEW

**Comment by hyunbumy** [comment]
untitled1



4K Image rendered in about 0.5 sec with reflection and refraction using recursive RT on CUDA

**Comment by avnishn** [comment]
we should try the iterative code on HPC
What do you think? perhaps it works better in the long term for more complex frames, but its hard to say right now because I still need to look into bring in more complex frames

**Comment by avnishn** [comment]
I'll take a look at this tomorrow before noon

**Comment by avnishn** [comment]
If its possible, could you tell me what parts of the code you changed from recursive to iterative? 
I want to see the change you made with regards to that, so that I can potentially pinpoint whats causing the slowdown and where we can do a speedup @hyunbumy

**Review by razugo — APPROVED** [review]

**Comment by razugo** [comment]
lgtm

**Comment by hyunbumy** [comment]
@avnishn
There are two files cudaRT and cudaRTIter. The first one is recursive and the second is iterative.

There is actually a profiling tool called nvprof or something if youre interested.

**Pull request merged**
